### PR TITLE
Added convenience function for requesting a single line of user input

### PR DESCRIPTION
**Pull request by bavovanachte**
Proposal for a user input helper function.

Not sure if this matches your strategy, so I didn't update the docs on this yet (therefore marked as WIP).

### CODE REVIEW

**Comment by bavovanachte** [comment]
@npcole is this project still planned to be maintained?

**Comment by npcole** [comment]
Yes.  We are long overdue a new release but it is still maintained.

The convenience function is a good idea.

**Comment by npcole** [comment]
I'm about to do a new release to fix a number of issues. Is this still a pull request you would like included?

**Comment by bavovanachte** [comment]
It would still make sense I think, yes. The PR doesn't have a doc update though (and I likely won't be able to get to a computer this weekend)

**Comment by npcole** [comment]
It's a good idea. I'm trying to prepare a new release. Would you like this
in it?

**Comment by npcole** [comment]
I'll likely be finalizing a release this weekend.

**Comment by bavovanachte** [comment]
Added documentation. Please let me know if there is something else I need to add.

**Pull request merged**
